# Generated by GitHub Copilot

import uuid
from django.db import migrations, models


def create_default_role_definitions(apps, schema_editor):
    RoleDefinition = apps.get_model("accounts", "RoleDefinition")
    defaults = [
        {
            "code": "admin",
            "name": "Administrator",
            "description": "Full administrative access.",
        },
        {
            "code": "finance",
            "name": "Finance staff",
            "description": "Finance team access.",
        },
        {
            "code": "auditor",
            "name": "Auditor",
            "description": "Audit and review access.",
        },
        {
            "code": "viewer",
            "name": "Viewer",
            "description": "Read-only access.",
        },
    ]

    for role in defaults:
        RoleDefinition.objects.update_or_create(code=role["code"], defaults=role)


def delete_default_role_definitions(apps, schema_editor):
    RoleDefinition = apps.get_model("accounts", "RoleDefinition")
    RoleDefinition.objects.filter(code__in=["admin", "finance", "auditor", "viewer"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.RunPython(create_default_role_definitions, delete_default_role_definitions),
    ]
