# Generated by Django 5.0.4 on 2026-04-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_email_otp_groups'),
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
        migrations.RemoveConstraint(
            model_name='grouppermission',
            name='unique_group_doctype_action',
        ),
        migrations.RemoveConstraint(
            model_name='usergroupmembership',
            name='unique_user_group',
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='grouppermission',
            unique_together={('group', 'document_type', 'action')},
        ),
        migrations.AlterUniqueTogether(
            name='usergroupmembership',
            unique_together={('user', 'group')},
        ),
        migrations.DeleteModel(
            name='UserActivityLog',
        ),
    ]
