# Generated by Django 5.0.4 on 2026-04-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ldap_dn',
        ),
        migrations.AddField(
            model_name='user',
            name='job_description',
            field=models.CharField(blank=True, db_column='ldap_dn', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='action',
            field=models.CharField(choices=[('admin', 'Administrator access'), ('view', 'View documents'), ('upload', 'Upload documents'), ('edit', 'Edit metadata'), ('delete', 'Delete / void documents'), ('approve', 'Approve in workflow'), ('download', 'Download files'), ('comment', 'Add comments'), ('archive', 'Archive documents')], max_length=20),
        ),
    ]
