# Generated by Django 5.0.4 on 2026-05-06 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_ldap_dn_user_job_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDelegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delegations', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_incoming', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_outgoing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['delegator', 'starts_at', 'ends_at'], name='accounts_us_delegat_abb7ff_idx'), models.Index(fields=['delegate', 'starts_at', 'ends_at'], name='accounts_us_delegat_b0895d_idx'), models.Index(fields=['is_active'], name='accounts_us_is_acti_20c04f_idx')],
            },
        ),
    ]
