# Generated by Django on 2026-05-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userdelegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdelegation',
            name='comment',
            field=models.TextField(default='', blank=True),
        ),
    ]
