# Generated by Codex on 2026-05-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def ensure_hod_group(apps, schema_editor):
    UserGroup = apps.get_model("accounts", "UserGroup")
    UserGroupMembership = apps.get_model("accounts", "UserGroupMembership")
    Department = apps.get_model("accounts", "Department")

    group, _ = UserGroup.objects.get_or_create(
        name="HOD",
        defaults={
            "description": "Built-in group containing the active heads of department.",
            "is_active": True,
        },
    )
    updates = {}
    if not group.description:
        updates["description"] = "Built-in group containing the active heads of department."
    if not group.is_active:
        updates["is_active"] = True
    if updates:
        UserGroup.objects.filter(pk=group.pk).update(**updates)

    head_ids = set(
        Department.objects
        .filter(head__isnull=False, head__is_active=True)
        .values_list("head_id", flat=True)
    )
    for head_id in head_ids:
        UserGroupMembership.objects.update_or_create(
            user_id=head_id,
            group_id=group.id,
            defaults={"expires_at": None},
        )
    UserGroupMembership.objects.filter(
        group_id=group.id
    ).exclude(user_id__in=head_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_add_userdelegation_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(ensure_hod_group, migrations.RunPython.noop),
    ]
