# Generated by Django 6.0.4 on 2026-05-25 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_department_head_and_hod_group'),
        ('documents', '0014_documentrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20)),
                ('time_format', models.CharField(choices=[('12-hour', '12-hour'), ('24-hour', '24-hour')], default='12-hour', max_length=20)),
                ('default_page', models.CharField(choices=[('dashboard', 'Dashboard'), ('my_tasks', 'My Tasks'), ('all_documents', 'All Documents')], default='dashboard', max_length=50)),
                ('notify_document_approvals', models.BooleanField(default=True)),
                ('notify_document_rejected', models.BooleanField(default=True)),
                ('notify_task_assignments', models.BooleanField(default=True)),
                ('notify_system_announcements', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.AddField(
            model_name='userdelegation',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='If null, delegates all tasks. If set, delegates only tasks for this document type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations', to='documents.documenttype'),
        ),
    ]
