# Generated by Codex on 2026-05-29

import apps.accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_userpreference_userdelegation_document_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSignature",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to=apps.accounts.models.signature_upload_path)),
                ("method", models.CharField(choices=[("draw", "Drawn"), ("type", "Typed"), ("upload", "Uploaded")], max_length=20)),
                ("typed_name", models.CharField(blank=True, max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="signatures", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="usersignature",
            index=models.Index(fields=["user", "is_active"], name="accounts_us_user_id_2bb1b9_idx"),
        ),
    ]
