# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_usersignature"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="grouppermission",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="grouppermission",
            name="stage",
            field=models.CharField(
                db_index=True,
                default="any",
                help_text="Document lifecycle stage this permission applies to. 'any' preserves legacy behaviour.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="grouppermission",
            name="action",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator access"),
                    ("view", "View documents"),
                    ("upload", "Upload documents"),
                    ("submit", "Submit for approval"),
                    ("edit", "Edit metadata"),
                    ("delete", "Delete / void documents"),
                    ("approve", "Approve in workflow"),
                    ("download", "Download files"),
                    ("comment", "Add comments"),
                    ("archive", "Archive documents"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grouppermission",
            unique_together={("group", "document_type", "stage", "action")},
        ),
        migrations.AlterModelOptions(
            name="grouppermission",
            options={"ordering": ["group", "document_type", "stage", "action"]},
        ),
    ]
