# Generated by Django 5.0.4 on 2026-06-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_group_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='sees_all_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='stage',
            field=models.CharField(choices=[('any', 'All stages'), ('creation', 'Creation'), ('approval', 'For approval'), ('after_approval', 'After approval')], db_index=True, default='any', help_text="Document lifecycle stage this permission applies to. 'any' applies to all stages.", max_length=50),
        ),
    ]
