# Generated by Django 5.0.4 on 2026-09-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oidc_sub',
            field=models.CharField(blank=True, db_index=True, help_text='Keycloak subject (sub) UUID — stable OIDC identity link.', max_length=255, null=True, unique=True),
        ),
    ]
