# Generated by Django 5.0.4 on 2026-09-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_mode', models.CharField(choices=[('full', 'Full'), ('procurement', 'Procurement'), ('forms_only', 'Forms Only'), ('custom', 'Custom')], default='full', max_length=20)),
                ('enabled_modules', models.JSONField(default=list)),
                ('product_name', models.CharField(default='FlaxemDMS', max_length=100)),
                ('primary_color', models.CharField(default='#1e40af', max_length=7)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Deployment',
                'verbose_name_plural': 'Client Deployments',
            },
        ),
    ]
