# Generated by Django 5.0.4 on 2026-07-08 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0040_dmssettings_session_warning_minutes'),
        ('sunsystems', '0002_sunsystemsconnection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalposting',
            options={'ordering': ['stage', '-created_at']},
        ),
        migrations.AddField(
            model_name='journalposting',
            name='stage',
            field=models.PositiveSmallIntegerField(default=1, help_text='Posting stage number (1 = advance / first approval, 2 = retirement, …).'),
        ),
        migrations.AddField(
            model_name='journalposting',
            name='stage_label',
            field=models.CharField(blank=True, help_text="Human-readable stage name from the mapping (e.g. 'Advance', 'Retirement').", max_length=64),
        ),
        migrations.AlterField(
            model_name='journalposting',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_postings', to='documents.document'),
        ),
        migrations.AlterUniqueTogether(
            name='journalposting',
            unique_together={('document', 'stage')},
        ),
    ]
