# Generated by Django 5.0.4 on 2026-09-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunsystems', '0005_alter_paymentrun_reference_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrun',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending approval'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending_approval', max_length=24),
        ),
    ]
