# Generated by Devin

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunsystems', '0006_alter_paymentrun_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrun',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending_approval', 'Pending approval'),
                    ('rejected', 'Rejected'),
                    ('approved', 'Approved'),
                    ('processing', 'Processing'),
                    ('paid', 'Paid'),
                    ('failed', 'Failed')
                ],
                default='pending_approval',
                max_length=32
            ),
        ),
    ]
