# Generated by Django 5.0.4 on 2026-09-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunsystems', '0007_add_rejected_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrun',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending approval'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending_approval', max_length=24),
        ),
    ]
