# Generated by Django 5.0.4 on 2026-09-17 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsageSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key_id', models.CharField(db_index=True, max_length=100)),
                ('client_name', models.CharField(max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('cache_read_tokens', models.BigIntegerField(default=0)),
                ('cache_write_tokens', models.BigIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('cost_is_estimated', models.BooleanField(default=False, help_text='True when cost_usd was estimated from tokens rather than Cost API.')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'client_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200)),
                ('api_key_id', models.CharField(help_text='Anthropic Console API key id (apikey_…), used to group Usage API rows.', max_length=100, unique=True)),
                ('workspace_id', models.CharField(blank=True, default='', help_text='Optional Anthropic workspace id (wrkspc_…) for Cost API attribution.', max_length=100)),
                ('monthly_limit_usd', models.DecimalField(decimal_places=2, default=0, help_text='Reference monthly spend cap for alerts. Hard stop remains Anthropic workspace limits.', max_digits=10)),
                ('alert_email', models.EmailField(blank=True, default='', help_text='Override recipient for 90% spend alerts. Empty → FLAXEM_OPS_ALERT_EMAIL.', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['client_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='apiusagesnapshot',
            constraint=models.UniqueConstraint(fields=('api_key_id', 'date'), name='billing_apiusagesnapshot_key_date_uniq'),
        ),
    ]
