# Generated by Django 5.0.4 on 2026-04-15 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='workflow_template',
            field=models.ForeignKey(blank=True, help_text='Primary approval workflow for this document type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_types', to='workflows.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document'),
        ),
        migrations.AddField(
            model_name='metadatafield',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_fields', to='documents.documenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='documents.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='metadatafield',
            unique_together={('document_type', 'key')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'document_type'], name='documents_d_status_93c4bf_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['supplier', 'document_date'], name='documents_d_supplie_1b7e51_idx'),
        ),
    ]
