# Generated by Django 5.0.4 on 2026-04-21 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
        ('documents', '0004_document_ocr_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_scanned',
            field=models.BooleanField(db_index=True, default=False, help_text='True when the document is a scanned image or image-based PDF. The OCR pipeline runs automatically.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_self_upload',
            field=models.BooleanField(db_index=True, default=False, help_text='Personal/non-approval upload. Visible only to uploader and admins.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='', help_text='Current state of the OCR text-extraction pipeline.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_self_upload', 'uploaded_by'], name='documents_d_is_self_d4340e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_scanned', 'ocr_status'], name='documents_d_is_scan_654b6e_idx'),
        ),
    ]
