# Generated by Django 5.0.4 on 2026-05-06 09:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_documenttype_personal_type_and_metadata_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(blank=True, default='#6366f1', max_length=7)),
                ('icon', models.CharField(blank=True, default='folder', max_length=40)),
                ('is_favourites', models.BooleanField(default=False, help_text='True for the auto-created Favourites folder.')),
                ('is_system', models.BooleanField(default=False, help_text='True for any system-managed folder (Favourites included).')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Sort order within the parent level.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentfolder')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFolderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_items', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_items', to='documents.document')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.documentfolder')),
            ],
            options={
                'ordering': ['position', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFavourite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Incremented each time the user opens this document.')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', 'added_at'], name='documents_d_user_id_f0f7ee_idx'), models.Index(fields=['user', 'access_count'], name='documents_d_user_id_fedb6a_idx')],
                'unique_together': {('user', 'document')},
            },
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['owner', 'parent'], name='documents_d_owner_i_c61e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['owner', 'is_favourites'], name='documents_d_owner_i_5517cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentfolder',
            unique_together={('owner', 'parent', 'name')},
        ),
        migrations.AddIndex(
            model_name='documentfolderitem',
            index=models.Index(fields=['folder', 'position'], name='documents_d_folder__c3cbb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentfolderitem',
            unique_together={('folder', 'document')},
        ),
    ]
