# Generated by Django 5.0.4 on 2026-05-15 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_documentfolder_documentfolderitem_documentfavourite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('review', 'Review'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('total_files', models.PositiveSmallIntegerField(default=0)),
                ('successful_uploads', models.PositiveSmallIntegerField(default=0)),
                ('failed_uploads', models.PositiveSmallIntegerField(default=0)),
                ('approved_count', models.PositiveSmallIntegerField(default=0)),
                ('rejected_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('common_tags', models.ManyToManyField(blank=True, related_name='bulk_uploads', to='documents.tag')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_uploads', to='documents.documenttype')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'uploaded_by'], name='documents_b_status_ab5854_idx')],
            },
        ),
    ]
