# Generated by Django 5.0.4 on 2026-05-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_bulkupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="bulk_upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.bulkupload",
            ),
        ),
    ]
