# Generated by Django 6.0.4 on 2026-05-23 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_bulk_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('view', 'View only'), ('download', 'View and download')], default='view', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_shares_received', to=settings.AUTH_USER_MODEL)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_shares_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'revoked_at', 'expires_at'], name='documents_d_recipie_c99222_idx'), models.Index(fields=['document', 'revoked_at'], name='documents_d_documen_82f895_idx')],
                'unique_together': {('document', 'recipient')},
            },
        ),
    ]
