# Generated by Django 6.0.4 on 2026-05-23 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_documentshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('supports', 'Supports'), ('references', 'References'), ('supersedes', 'Supersedes'), ('linked-to', 'Linked to')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_relationships_created', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='documents.document')),
                ('target_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='documents.document')),
            ],
            options={
                'ordering': ['relation_type', '-created_at'],
                'indexes': [models.Index(fields=['source_document', 'relation_type'], name='documents_d_source__ef2fd9_idx'), models.Index(fields=['target_document', 'relation_type'], name='documents_d_target__96a32c_idx')],
                'unique_together': {('source_document', 'target_document', 'relation_type')},
            },
        ),
    ]
