# Generated by Django 6.0.4 on 2026-05-26 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_doctypecolor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DMSSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('watermark_enabled', models.BooleanField(default=False)),
                ('watermark_text', models.CharField(blank=True, default='CONFIDENTIAL', max_length=120)),
                ('watermark_opacity', models.PositiveSmallIntegerField(default=15)),
                ('watermark_position', models.CharField(choices=[('diagonal', 'Diagonal'), ('center', 'Center'), ('footer', 'Footer')], default='diagonal', max_length=20)),
                ('watermark_apply_to_previews', models.BooleanField(default=True)),
                ('allow_duplicate_uploads', models.BooleanField(default=False)),
                ('auto_archive_enabled', models.BooleanField(default=False)),
                ('auto_archive_after_days', models.PositiveIntegerField(default=365)),
                ('require_metadata_on_upload', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dms_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DMS settings',
                'verbose_name_plural': 'DMS settings',
            },
        ),
    ]
