# Generated by Django 6.0.4 on 2026-05-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_dmssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmssettings',
            name='signed_file_urls_enabled',
            field=models.BooleanField(default=False, help_text='Issue short-lived signed file URLs for browser contexts that cannot send Authorization headers.'),
        ),
    ]
