# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0017_dmssettings_signed_file_urls_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkupload",
            name="mode",
            field=models.CharField(
                choices=[
                    ("same_type", "Same document type"),
                    ("related_set", "Related document set"),
                ],
                db_index=True,
                default="same_type",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bulkupload",
            name="shared_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
