# Generated by Codex on 2026-05-30

from django.db import migrations, models


DEFAULT_ACCESS_STAGES = [
    {"key": "creation", "name": "Creation", "statuses": ["draft", "pending_review", "returned", "rejected"]},
    {"key": "approval", "name": "For approval", "statuses": ["pending_approval"]},
    {"key": "approved", "name": "After approval", "statuses": ["approved", "archived"]},
]


def seed_access_stages(apps, schema_editor):
    DMSSettings = apps.get_model("documents", "DMSSettings")
    settings, _ = DMSSettings.objects.get_or_create(pk=1)
    if not settings.access_stages:
        settings.access_stages = DEFAULT_ACCESS_STAGES
        settings.save(update_fields=["access_stages", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0018_bulkupload_mode_shared_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="dmssettings",
            name="bulk_scan_submit_for_approval",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, reviewed bulk scan documents are immediately submitted to approval workflows.",
            ),
        ),
        migrations.AddField(
            model_name="dmssettings",
            name="access_stages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Admin-configurable document access stages used by group permissions.",
            ),
        ),
        migrations.RunPython(seed_access_stages, migrations.RunPython.noop),
    ]
