# Generated by Django 6.0.4 on 2026-06-01 07:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_dmssettings_access_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRelationshipRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('supports', 'Supports'), ('references', 'References'), ('supersedes', 'Supersedes'), ('linked-to', 'Linked to')], default='references', max_length=30)),
                ('source_field_key', models.CharField(help_text='Field on the source document, for example po_number or transaction_reference.', max_length=100)),
                ('target_field_key', models.CharField(help_text='Field on the target document to compare with the source field.', max_length=100)),
                ('match_operator', models.CharField(choices=[('equals', 'Equals')], default='equals', max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('require_confirmation', models.BooleanField(default=True, help_text='When true, matches are suggested for user confirmation instead of created automatically.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationship_rules', to='documents.documenttype')),
                ('target_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationship_rules', to='documents.documenttype')),
            ],
            options={
                'ordering': ['source_document_type__name', 'target_document_type__name', 'source_field_key'],
                'indexes': [models.Index(fields=['source_document_type', 'is_active'], name='documents_d_source__dd4fc6_idx'), models.Index(fields=['target_document_type', 'is_active'], name='documents_d_target__f1108f_idx')],
                'unique_together': {('source_document_type', 'target_document_type', 'relation_type', 'source_field_key', 'target_field_key')},
            },
        ),
    ]
