# Generated by Django 5.0.4 on 2026-06-05 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_documenttype_title_field_filename_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dmssettings',
            name='trash_auto_empty_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dmssettings',
            name='trash_retention_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trashed_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
