# Generated by Django 5.0.4 on 2026-06-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_dmssettings_trash_auto_empty_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmssettings',
            name='rbac_single_stage',
            field=models.BooleanField(default=False),
        ),
    ]
