# Generated by Django 5.0.4 on 2026-06-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_signaturerequest_signaturerequestsigner'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='max_file_size_mb',
            field=models.PositiveSmallIntegerField(default=25, help_text='Maximum upload size (in MB) for documents of this type, including new versions.'),
        ),
    ]
