# Generated by Django 5.0.4 on 2026-06-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_documenttype_max_file_size_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmssettings',
            name='organization_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dmssettings',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
