# Generated by Django 5.0.4 on 2026-06-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_dmssettings_purge_trashed_duplicates_on_reupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmssettings',
            name='session_idle_timeout_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Sign users out after this many minutes of inactivity. 0 disables the idle timeout.'),
        ),
        migrations.AddField(
            model_name='dmssettings',
            name='session_lifetime_minutes',
            field=models.PositiveIntegerField(default=360, help_text='Absolute maximum session duration from sign-in, in minutes.'),
        ),
    ]
