# Generated by Django 5.0.4 on 2026-06-25 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_dmssettings_session_idle_timeout_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='signaturerequestsigner',
            index=models.Index(fields=['signer', 'status'], name='documents_s_signer__51dcd6_idx'),
        ),
    ]
