# Generated by Django 5.0.4 on 2026-06-26 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0034_backfill_document_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('connection', models.JSONField(blank=True, default=dict, help_text='IMAP connection settings: host, port, use_ssl, username, password, folder, search_criteria.')),
                ('auto_classify', models.BooleanField(default=False, help_text='Attempt to infer the document type from content instead of always using the default.')),
                ('sender_supplier_map', models.JSONField(blank=True, default=dict, help_text='Map of sender email/domain -> supplier name, used to pre-fill the supplier field.')),
                ('related_set_attachments', models.BooleanField(default=True, help_text='Import a multi-attachment email as one related document set.')),
                ('max_messages_per_poll', models.PositiveIntegerField(default=50, help_text='Ceiling on messages processed in one poll. 0 = no limit.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only active mailboxes are polled by the scheduled job.')),
                ('poll_status', models.CharField(choices=[('idle', 'Idle'), ('polling', 'Polling'), ('ok', 'Last poll succeeded'), ('error', 'Last poll failed')], db_index=True, default='idle', max_length=20)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_seen_uid', models.PositiveBigIntegerField(default=0)),
                ('last_imported_count', models.PositiveIntegerField(default=0)),
                ('last_skipped_count', models.PositiveIntegerField(default=0)),
                ('last_failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Owner that imported documents are attributed to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailboxes', to=settings.AUTH_USER_MODEL)),
                ('default_document_type', models.ForeignKey(blank=True, help_text='Document type imported attachments are filed under. Null = UNCLASS placeholder.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailboxes', to='documents.documenttype')),
            ],
            options={
                'verbose_name_plural': 'mailboxes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngestedEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(db_index=True, max_length=512)),
                ('imap_uid', models.PositiveBigIntegerField(default=0)),
                ('sender', models.CharField(blank=True, max_length=320)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('raw_email', models.FileField(blank=True, help_text='Original RFC-822 message stored for compliance/audit.', null=True, upload_to='ingested_emails/')),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('skipped', 'Skipped'), ('partial', 'Imported with errors'), ('failed', 'Failed')], db_index=True, default='imported', max_length=20)),
                ('attachment_count', models.PositiveSmallIntegerField(default=0)),
                ('documents_created', models.PositiveSmallIntegerField(default=0)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingested_emails', to='documents.bulkupload')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingested_emails', to='documents.mailbox')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mailbox',
            index=models.Index(fields=['is_active', 'poll_status'], name='documents_m_is_acti_e5e67d_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestedemail',
            index=models.Index(fields=['mailbox', 'status'], name='documents_i_mailbox_ca90c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingestedemail',
            constraint=models.UniqueConstraint(fields=('mailbox', 'message_id'), name='uniq_mailbox_message_id'),
        ),
    ]
