# Generated by Django 5.0.4 on 2026-06-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_mailbox_ingestedemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='sender_allowlist',
            field=models.JSONField(blank=True, default=list, help_text='If non-empty, only emails whose sender address/domain appears here are ingested; everything else is skipped. Empty = accept all senders.'),
        ),
    ]
