# Generated by Django 5.0.4 on 2026-06-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_mailbox_sender_allowlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='ingest_history',
            field=models.BooleanField(default=False, help_text="Import messages already in the mailbox at the time it is created. Off (default) ingests only mail that arrives afterwards, so a busy existing inbox doesn't pull its whole backlog on the first poll."),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='ingest_since',
            field=models.DateField(blank=True, help_text='Only import messages received on or after this date. Blank = no date limit.', null=True),
        ),
    ]
