# Generated by Django 5.0.4 on 2026-06-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_mailbox_ingest_history_mailbox_ingest_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='last_seen_cursor',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='protocol',
            field=models.CharField(choices=[('imap', 'IMAP'), ('graph', 'Microsoft Graph')], db_index=True, default='imap', help_text='Mail backend used to reach this mailbox.', max_length=10),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='connection',
            field=models.JSONField(blank=True, default=dict, help_text='Connection settings. IMAP: host, port, use_ssl, username, password, folder. Microsoft Graph: tenant_id, client_id, client_secret, mailbox (user principal name), folder.'),
        ),
    ]
