# Generated by Django 5.0.4 on 2026-06-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_mailbox_last_seen_cursor_mailbox_protocol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='allowed_attachment_extensions',
            field=models.JSONField(blank=True, default=list, help_text="If non-empty, only attachments with these file extensions are imported (e.g. ['pdf', 'png']); others are ignored. Empty = all."),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
