# Generated by Django 5.0.4 on 2026-06-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_mailbox_allowed_attachment_extensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmssettings',
            name='session_warning_minutes',
            field=models.PositiveIntegerField(default=3, help_text='Warn users this many minutes before their session ends. 0 disables the warning.'),
        ),
    ]
