# Generated by Django 5.0.4 on 2026-08-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0042_dmssettings_idp_policy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mailbox',
            new_name='documents_m_is_acti_cbc485_idx',
            old_name='documents_m_is_acti_auto_po_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('needs_manual', 'Needs manual entry'), ('failed', 'Failed')], db_index=True, default='', help_text='Current state of the OCR text-extraction pipeline.', max_length=20),
        ),
    ]
