# Generated by Django 5.0.4 on 2026-09-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0045_idp_usage_daily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmssettings',
            name='idp_anthropic_api_key',
            field=models.CharField(blank=True, default='', help_text='Per-tenant Anthropic workspace API key (operator-managed). When empty, falls back to ANTHROPIC_API_KEY in the environment.', max_length=255),
        ),
    ]
