# Generated by Django 5.0.4 on 2026-06-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_engine', '0003_template_document_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documenttemplate',
            new_name='templates_e_type_0db665_idx',
            old_name='tmpl_type_active_idx',
        ),
        migrations.RenameIndex(
            model_name='documenttemplate',
            new_name='templates_e_categor_076151_idx',
            old_name='tmpl_cat_active_idx',
        ),
        migrations.RenameIndex(
            model_name='documenttemplate',
            new_name='templates_e_documen_9ed282_idx',
            old_name='tmpl_doctype_active_idx',
        ),
    ]
