# Generated by Django 5.0.4 on 2026-09-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_engine', '0006_documenttemplate_sunsystems'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='workflow_type',
            field=models.CharField(choices=[('imprest', 'Imprest (Request → Retirement)'), ('requisition', 'Requisition (Requisition → RFQ → LPO)')], default='imprest', help_text='Workflow type for this template: determines available process steps.', max_length=20),
        ),
    ]
