# Generated by Django 5.0.4 on 2026-04-11 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('document.created', 'Document Created'), ('document.viewed', 'Document Viewed'), ('document.downloaded', 'Document Downloaded'), ('document.updated', 'Document Updated'), ('document.deleted', 'Document Deleted'), ('document.submitted', 'Submitted for Approval'), ('workflow.approved', 'Workflow Step Approved'), ('workflow.rejected', 'Workflow Step Rejected'), ('document.archived', 'Document Archived'), ('document.version_uploaded', 'New Version Uploaded'), ('document.version_restored', 'Version Restored'), ('user.login', 'User Login'), ('user.login_failed', 'Login Failed'), ('user.mfa_enabled', 'MFA Enabled'), ('permission.changed', 'Permission Changed')], db_index=True, max_length=60)),
                ('object_type', models.CharField(blank=True, max_length=60)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'default_permissions': ('view',),
            },
        ),
    ]
