# Generated by Django 5.0.4 on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_alter_auditlog_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="event",
            field=models.CharField(
                choices=[
                    ("document.created", "Document Created"),
                    ("document.viewed", "Document Viewed"),
                    ("document.previewed", "Document File Previewed (inline)"),
                    ("document.downloaded", "Document File Downloaded (attachment)"),
                    ("document.printed", "Document Print Requested"),
                    ("document.updated", "Document Updated"),
                    ("document.deleted", "Document Deleted"),
                    ("document.submitted", "Submitted for Approval"),
                    ("workflow.approved", "Workflow Step Approved"),
                    ("workflow.rejected", "Workflow Step Rejected"),
                    ("workflow.returned", "Workflow Step Returned"),
                    ("workflow.held", "Workflow Step Held"),
                    ("workflow.released", "Workflow Step Released"),
                    ("workflow.delegated", "Workflow Tasks Delegated"),
                    ("workflow.reassigned", "Workflow Tasks Reassigned"),
                    ("document.archived", "Document Archived"),
                    ("document.version_uploaded", "New Version Uploaded"),
                    ("document.version_restored", "Version Restored"),
                    ("user.login", "User Login"),
                    ("user.login_failed", "Login Failed"),
                    ("user.mfa_enabled", "MFA Enabled"),
                    ("permission.changed", "Permission Changed"),
                ],
                db_index=True,
                max_length=60,
            ),
        ),
    ]
