# Generated by Django 5.0.4 on 2026-08-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_alter_auditlog_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event',
            field=models.CharField(choices=[('document.created', 'Document Created'), ('document.viewed', 'Document Viewed'), ('document.previewed', 'Document File Previewed (inline)'), ('document.downloaded', 'Document File Downloaded (attachment)'), ('document.printed', 'Document Print Requested'), ('document.updated', 'Document Updated'), ('document.deleted', 'Document Deleted'), ('document.restored', 'Document Restored from Trash'), ('document.purged', 'Document Permanently Deleted'), ('document.submitted', 'Submitted for Approval'), ('document.bulk_uploaded', 'Document Bulk Uploaded'), ('document.bulk_reviewed', 'Bulk Upload Reviewed'), ('document.preview_queued', 'Document Preview Queued'), ('document.ocr_queued', 'Document OCR Queued'), ('document.ocr_completed', 'Document OCR Completed'), ('document.ocr_failed', 'Document OCR Failed'), ('document.edit_lock_acquired', 'Document Edit Lock Acquired'), ('document.edit_lock_released', 'Document Edit Lock Released'), ('workflow.approved', 'Workflow Step Approved'), ('workflow.rejected', 'Workflow Step Rejected'), ('workflow.returned', 'Workflow Step Returned'), ('workflow.held', 'Workflow Step Held'), ('workflow.released', 'Workflow Step Released'), ('workflow.cancelled', 'Workflow Cancelled'), ('workflow.delegated', 'Workflow Tasks Delegated'), ('workflow.reassigned', 'Workflow Tasks Reassigned'), ('document.archived', 'Document Archived'), ('document.version_uploaded', 'New Version Uploaded'), ('document.version_restored', 'Version Restored'), ('document.version_preview_queued', 'Document Version Preview Queued'), ('user.login', 'User Login'), ('user.login_failed', 'Login Failed'), ('user.mfa_enabled', 'MFA Enabled'), ('user.created', 'User Created'), ('user.deleted', 'User Deleted'), ('user.password_reset', 'User Password Reset'), ('user.activated', 'User Activated'), ('user.deactivated', 'User Deactivated'), ('permission.changed', 'Permission Changed'), ('group.permission_granted', 'Group Permission Granted'), ('group.permission_revoked', 'Group Permission Revoked'), ('group.permission_updated', 'Group Permissions Updated'), ('signature.request_created', 'Signature Request Created'), ('signature.request_signed', 'Signature Request Signed'), ('signature.request_completed', 'Signature Request Completed'), ('signature.request_declined', 'Signature Request Declined'), ('signature.request_cancelled', 'Signature Request Cancelled'), ('audit.exported', 'Audit Log Exported')], db_index=True, max_length=60),
        ),
    ]
