# Generated by Django 5.0.4 on 2026-04-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtask',
            name='held_until',
            field=models.DateTimeField(blank=True, help_text='Auto-release hold at this time. Null = indefinite (not used).', null=True),
        ),
    ]
