# Generated by Django 5.0.4 on 2026-04-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        # Compatibility no-op: 0001_initial already creates WorkflowTask.held_until.
        # Keeping this migration preserves the published migration graph without
        # issuing a duplicate ALTER TABLE on fresh MySQL databases.
    ]
