# Generated by Django 5.0.4 on 2026-04-17 10:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_add_held_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Compatibility no-op: 0001_initial already creates these models and
        # relationships. Leaving this migration in place preserves dependencies.
    ]
