# Generated by Django 5.0.4 on 2026-04-17 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_add_missing_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtask',
            name='return_to',
            field=models.CharField(
                choices=[
                    ('previous_step', 'Previous Approver'),
                    ('uploader', 'Document Uploader'),
                    ('same_step', 'Same Approver'),
                ],
                default='previous_step',
                help_text='Where to return the document if rejected/returned',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='workflowtaskaction',
            name='return_to',
            field=models.CharField(
                choices=[
                    ('previous_step', 'Previous Approver'),
                    ('uploader', 'Document Uploader'),
                    ('same_step', 'Same Approver'),
                ],
                blank=True,
                help_text='Where the document was returned to',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='WorkflowTaskActionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflows.workflowtaskaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
