# Generated by Django 5.0.4 on 2026-04-21 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_optimize_workflow_logic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtask',
            name='held_until',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the hold was placed; cleared on release.', null=True),
        ),
        migrations.AlterField(
            model_name='workflowtask',
            name='return_to',
            field=models.CharField(choices=[('previous_step', 'Previous Approver'), ('uploader', 'Document Uploader'), ('same_step', 'Same Approver')], default='previous_step', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowtaskaction',
            name='return_to',
            field=models.CharField(blank=True, choices=[('previous_step', 'Previous Approver'), ('uploader', 'Document Uploader'), ('same_step', 'Same Approver')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowtaskactionnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_action_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='workflowtaskactionnotification',
            unique_together={('action', 'user')},
        ),
    ]
