# Generated by Django 5.0.4 on 2026-04-21 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
        ('workflows', '0005_alter_workflowtask_held_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowstep',
            name='assignee_role',
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='assignee_group',
            field=models.ForeignKey(blank=True, help_text='The group whose members are eligible to action this step.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='accounts.usergroup'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='assignee_type',
            field=models.CharField(choices=[('group_member', 'Any member of group'), ('group_hod', 'Group HOD only'), ('specific_user', 'Specific user')], default='group_member', max_length=20),
        ),
    ]
