# Generated by Django 5.0.4 on 2026-04-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_remove_workflowstep_assignee_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowstep',
            name='assignee_group',
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='assignee_role',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='assignee_type',
            field=models.CharField(choices=[('any_role', 'Any user with role'), ('specific_user', 'Specific user')], default='any_role', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowtask',
            name='held_until',
            field=models.DateTimeField(blank=True, help_text='Hold timestamp - when approver manually releases, this is cleared.', null=True),
        ),
        migrations.AlterField(
            model_name='workflowtask',
            name='return_to',
            field=models.CharField(choices=[('previous_step', 'Previous Approver'), ('uploader', 'Document Uploader'), ('same_step', 'Same Approver')], default='previous_step', help_text='Where to return the document if rejected/returned', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowtaskaction',
            name='return_to',
            field=models.CharField(blank=True, choices=[('previous_step', 'Previous Approver'), ('uploader', 'Document Uploader'), ('same_step', 'Same Approver')], help_text='Where the document was returned to', max_length=20),
        ),
    ]
