# Generated by Codex on 2026-04-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("workflows", "0007_remove_workflowstep_assignee_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="assignee_group",
            field=models.ForeignKey(
                blank=True,
                help_text="The group responsible for this step.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_steps",
                to="accounts.usergroup",
            ),
        ),
        migrations.RemoveField(
            model_name="workflowstep",
            name="assignee_role",
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="assignee_type",
            field=models.CharField(
                choices=[
                    ("group_any", "Any member of group"),
                    ("group_all", "All members of group"),
                    ("group_specific", "Specific member of group"),
                    ("specific_user", "Specific user"),
                ],
                default="group_any",
                max_length=20,
            ),
        ),
    ]
