# Generated by Django 5.0.4 on 2026-04-25 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_ldap_dn_user_job_description_and_more'),
        ('workflows', '0008_group_based_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='allow_approve',
            field=models.BooleanField(default=True, help_text='Approver can approve at this step'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='allow_reject',
            field=models.BooleanField(default=True, help_text='Approver can reject at this step'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='allow_return',
            field=models.BooleanField(default=True, help_text='Approver can send back for review at this step'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='assignee_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='accounts.usergroup'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='assignee_type',
            field=models.CharField(choices=[('group_any', 'Any member of group'), ('group_all', 'All members of group'), ('group_specific', 'Specific member of group')], default='group_any', max_length=20),
        ),
    ]
