# Generated by Codex on 2026-05-29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_usersignature"),
        ("documents", "0017_dmssettings_signed_file_urls_enabled"),
        ("workflows", "0011_sync_rule_document_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="requires_signature",
            field=models.BooleanField(default=False, help_text="Approving this step must stamp the approver's saved e-signature onto the document."),
        ),
        migrations.CreateModel(
            name="DocumentSignature",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("page_number", models.PositiveIntegerField(default=1)),
                ("x", models.FloatField(default=0)),
                ("y", models.FloatField(default=0)),
                ("width", models.FloatField(default=180)),
                ("height", models.FloatField(default=72)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                ("action", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="document_signature", to="workflows.workflowtaskaction")),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="signatures", to="documents.document")),
                ("signed_version", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="signatures", to="documents.documentversion")),
                ("signer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="document_signatures", to=settings.AUTH_USER_MODEL)),
                ("source_signature", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="document_signatures", to="accounts.usersignature")),
                ("task", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="document_signature", to="workflows.workflowtask")),
            ],
            options={
                "ordering": ["signed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="documentsignature",
            index=models.Index(fields=["document", "signed_at"], name="workflows_d_documen_f82909_idx"),
        ),
        migrations.AddIndex(
            model_name="documentsignature",
            index=models.Index(fields=["signer", "signed_at"], name="workflows_d_signer__18e84b_idx"),
        ),
    ]
