# Generated by Django 5.0.4 on 2026-06-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0012_e_signatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='assignee_user_auto',
            field=models.BooleanField(default=False),
        ),
    ]
