# Generated by Django 5.0.4 on 2026-06-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0015_template_email_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='approver_email_body',
            field=models.TextField(blank=True, help_text='Custom body for the task-assignment email sent to approvers. Supports these placeholders: {approver_name}, {document_title}, {document_ref}, {step_name}, {instructions}, {document_url}. Leave blank to use the system default.'),
        ),
    ]
