# Generated by Django 5.0.4 on 2026-06-25 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0016_alter_workflowstep_approver_email_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(fields=['assigned_to', 'status'], name='workflows_w_assigne_1b0e2e_idx'),
        ),
    ]
