# Generated by Django 5.0.4 on 2026-09-03 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunsystems', '0005_alter_paymentrun_reference_prefix'),
        ('workflows', '0018_workflowrule_phase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowrule',
            options={'ordering': ['target_type', 'document_type', 'phase', 'amount_min', 'amount_max']},
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='payment_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instance', to='sunsystems.paymentrun'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='target_type',
            field=models.CharField(choices=[('document', 'Document'), ('payment_run', 'Payment run')], db_index=True, default='document', max_length=30),
        ),
        migrations.AddField(
            model_name='workflowrule',
            name='target_type',
            field=models.CharField(choices=[('document', 'Document'), ('payment_run', 'Payment run')], db_index=True, default='document', max_length=30),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='target_type',
            field=models.CharField(choices=[('document', 'Document'), ('payment_run', 'Payment run')], db_index=True, default='document', max_length=30),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instance', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='workflowrule',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_rules', to='documents.documenttype'),
        ),
    ]
