# Generated by Django 5.0.4 on 2026-04-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("task_assigned", "Task Assigned"),
                    ("workflow_complete", "Workflow Complete"),
                    ("document_returned", "Document Returned"),
                    ("document_held", "Document Held"),
                    ("hold_released", "Hold Released"),
                    ("hold_expired", "Hold Expired"),
                    ("task_overdue", "Task Overdue"),
                    ("workflow_action", "Workflow Action"),
                ],
                default="task_assigned",
                max_length=20,
            ),
        ),
    ]
