# Generated by Django 6.0.4 on 2026-05-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('workflow_complete', 'Workflow Complete'), ('document_returned', 'Document Returned'), ('document_held', 'Document Held'), ('hold_released', 'Hold Released'), ('hold_ending', 'Hold Ending Soon'), ('hold_expired', 'Hold Expired'), ('task_sla_warning', 'Task SLA Warning'), ('task_overdue', 'Task Overdue'), ('workflow_action', 'Workflow Action'), ('delegation', 'Delegation'), ('document_shared', 'Document Shared')], default='task_assigned', max_length=20),
        ),
    ]
