# Generated by Django 6.0.4 on 2026-05-20 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatnotification',
            name='chat_chatno_recipie_44d2d9_idx',
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', '-created_at'], name='chat_chatme_room_id_df087f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatnotification',
            index=models.Index(fields=['recipient', '-created_at'], name='chat_chatno_recipie_58d50e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['is_active', 'room_type', '-updated_at'], name='chat_chatro_is_acti_f16701_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['created_by', '-updated_at'], name='chat_chatro_created_977285_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroomparticipant',
            index=models.Index(fields=['user', 'is_active'], name='chat_chatro_user_id_fedd96_idx'),
        ),
    ]
